meta/people.json, src/components/NavBar.tsx, src/pages/about.tsx, src/pages/advisory.tsx
=> Adding all team bios, refactor bio info to single file

src/pages/contact.tsx
Fixes form submission which was redirecting to a 404 due to renaming the contact-us --> contact page.
=> fix: update submit redirect url

public/admin/index.html, src/components/Header.tsx, src/components/news/meta/BasicMeta.tsx
Add Plausible tag to prod branch.
=> feat: add plausible tag to head elements (3 locations)

meta/people.json, src/components/homepage/buttonwithicon/buttonwithicon.tsx, src/components/homepage/footer/footer.tsx, src/pages/index.tsx
just a couple of small updates, one related to #46
=> push small updates

public/styles/content.module.css, src/components/NavBar.tsx, src/components/homepage/buttonwithicon/buttonwithicon.tsx, src/components/homepage/cardwithimage/cardwithimage.tsx, src/components/homepage/footer/footer.tsx, src/pages/about.tsx, src/pages/advisory.tsx, src/pages/contact.tsx, src/pages/index.tsx, src/styles/globals.css, tailwind.config.js
See https://github.com/healthyregions/SDOHPlace/pull/67
=> Unify theme colors

src/components/NavBar.tsx
=> style: change mobile text to white #16

src/components/homepage/footer/footer.tsx
Temp fix for #47. Can add this back when we have a newsletter set up.
=> fix: comment out newsletter signup for now #47

src/pages/fellows.tsx
small update to title of fellows page
=> fix: update page title

content/posts/design-sprint.mdx, content/posts/introducing-the-sdoh-place-project.mdx, meta/people.json, src/components/NavBar.tsx, src/components/news/PostList.tsx, src/pages/about.tsx, src/pages/contact.tsx, src/pages/index.tsx
Added two members to core team, moved two from core to past-core, and adjusted everyone's short bio to only display six lines of text, five for those with last names that are long and wrap to two lines.
=> fix: add two people, set past-core, regularize short bio length

meta/people.json
@pengyin-shan adding you to core team! I should have had this in the last PR.
=> fix: add one more personnel

src/pages/about.tsx, src/pages/advisory.tsx, src/pages/contact.tsx, src/pages/index.tsx
This PR is for #143 . Based on call with designer, reduce the introduction font sizes on every page (except News) to `xl`.
=> #143: Change font-size of page introductions

meta/people.json, src/pages/about.tsx, src/pages/advisory.tsx, src/pages/contact.tsx, src/pages/index.tsx
Update font size in production.
=> Style updates (font size)

.gitignore, netlify.toml, package.json, public/admin/index.html, public/styles/posts.module.css, src/components/NavBar.tsx, src/components/ProfileImage.tsx, src/components/showcase/ShowcaseItem.tsx, src/lib/cms.ts, src/styles/globals.css, yarn.lock
Implements a dropdown menu pattern within the main navbar, closes #245.
Also set non-h1 headings to use Nunito instead of Fredoka.
=> 245 navbar dropdown

src/components/search/mapPanel/mapPanel.tsx
Slight improvement to the button style and label text, and this also _seems_ to fix a bug that was sometimes causing the menu modal to not fully close.
=> style: improve button style and label

meta/glossary.json, src/components/GlossaryPopover.tsx, src/components/search/detailPanel/iconTag.tsx, src/components/search/mapPanel/mapPanel.tsx, src/components/search/searchArea/infoPanel.tsx
Update explanatory text within the Discovery app.
=> 316 text content

src/pages/index.tsx
Link to guide that is now published.
=> feat: add link to new greenspace access guide

public/admin/config.yml, src/pages/index.tsx
adding home page link to greenspace access guide
=> Add link to greenspace guide

src/components/NavBar.tsx, src/pages/index.tsx
=> logo link fix

meta/_schema/sdohplace_schema.json, meta/interface/SolrObject.ts, src/components/search/detailPanel/headerRow.tsx, src/components/search/detailPanel/index.tsx, src/components/search/detailPanel/introCard.tsx, src/components/search/detailPanel/paragraphCard/paragraphCard.tsx, src/components/search/helper/ParseReferenceLink.tsx, src/components/search/mapPanel/mapPanelContent.tsx, src/components/search/searchArea/spatialResolutionCheck.tsx
Some updates to how references and other fields are displayed in the item details section.
=> References fix

config/prompt/prompt_message.js, src/components/map/dynamicMap.tsx, src/components/search/detailPanel/headerRow.tsx, src/components/search/mapPanel/mapPanelContent.tsx, src/components/search/resultsPanel/index.tsx, src/components/search/searchArea/enhancedSearch.tsx, src/components/search/searchArea/infoPanel.tsx
A handful of small style-related updates.
- remove italics within Discovery App text content (better for accessibility)
- remove extra margin/padding at top of results list to align with top of map
- remove left margin/padding from text content section below map
- change Overlays info icon to outline style
- add slide/collapse transition to share link box appearance
- remove scroll bar from map element
=> Style updates

src/components/map/helper/layers.tsx, src/components/search/mapPanel/mapPanelContent.tsx, src/components/search/searchArea/infoPanel.tsx
A few small updates to the overlay colors and the positioning of the dropdown menu.
=> Overlay & help tab style

src/components/map/dynamicMap.tsx, src/components/map/helper/layers.tsx, src/components/search/mapPanel/mapPanelContent.tsx, src/components/search/searchArea/infoPanel.tsx
Final style and description updates for overlays.
=> style: update overlay colors, refactor function args #491

src/components/map/dynamicMap.tsx, src/components/map/helper/layers.tsx
Address points raised in #497, as well as changing colors on a few asset layers.
=> 497 popup style

src/components/search/resultsPanel/resultCard.tsx
This PR is a test version for #507. I've removed the checkbox while preserving all other effects. @mradamcox @shubhamk008 @bodom0015  Feel free to test it here. I'll proceed with the version we prefer for the formal PR.
=> #507: Non-checkbox version

src/pages/team.tsx
Tiny change, decided to just do it quickly. @pengyin-shan You can merge this in after review.
=> fix: handle no link list in team person entry #524

config/prompt/prompt_message.js, config/prompt/prompt_message_chatgpt.js, meta/_schema/sdohplace_schema.json, src/components/search/helper/IconMatch.tsx, src/components/search/helper/themeIcons.tsx
=> feat: add Natural Environment subject icon and filter

src/components/search/detailPanel/paragraphCard/paragraphCard.tsx, src/components/search/discoveryArea.tsx
Applies a couple of the smaller requests mentioned in #514. I'll update that ticket to reflect these changes.
=> 514 style updates

src/components/search/searchArea/enhancedSearch.tsx
This PR addresses issue #535 and should be included in the next micro release. It enhances search functionality by adding search-type information along with search values and filter details. This improvement will enable a more precise analysis of user search behavior.
=> #535: Add more information in Plausible to watch the search behavior

src/lib/people.ts, src/pages/fellows.tsx
Hotfix to handle build issue on CMS content, where there are no links added to a fellow entry. Also linting.
=> fix: handle no links on fellows; show latest cohort first

src/components/map/dynamicMap.tsx
Quick addition of a basic scale control (using the bindings through react-map-gl: https://visgl.github.io/react-map-gl/docs/api-reference/maplibre/scale-control.
=> feat: add scale control #499

src/components/search/discoveryArea.tsx
Change the link for the survey form to new location.
=> chore: update link to feedback form

src/components/search/discoveryArea.tsx
=> fix build error

content/guides/public-transit-equity.mdx
PR #673 is currently un-testable, since our PR previews are not reading from the publish branch
* chore: copy existing guide content from publish to main
1. Navigate to the guide
* You should see that the guide content matches our current production system
=> chore: publish only the Public Transit Equity guide
