src/components/NavBar.tsx
src/components/homepage/buttonwithicon/buttonwithicon.tsx
src/components/homepage/cardwithimage/cardwithimage.tsx
src/components/homepage/footer/footer.tsx
src/pages/about.tsx
src/pages/advisory.tsx
src/pages/contact.tsx
src/pages/index.tsx
src/styles/globals.css
tailwind.config.js

Closes #63.
Consolidate all colors throughout the main site into using the theme defined via Tailwind. The intention was to reduce the number of raw hex codes in the codebase, and align the names of colors with our design materials, to reduce future confusion.
One note: the components that build the blog admin/editing interface (in `components/news/`) still have a lot of boilerplate colors from before. Those pages are not public-facing though, so much lower priority to implement our theme there.

refactor: align theme color names with design, implement in main content

---

meta/helper/solrObjects.ts
meta/interface/SolrObject.ts
meta/interface/SolrParent.ts
src/components/search/helper/SolrQueryBuilder.tsx
src/components/search/helper/SuggestedResultBuilder.tsx
src/components/search/interface/QueryObject.tsx
src/components/search/interface/SearchObject.tsx
src/components/search/interface/TermResult.tsx
src/components/search/parentList.tsx
src/components/search/searchArea.tsx
src/components/search/searchResults.tsx
src/pages/search/index.tsx

This PR includes a basic search box and backend that we can do further extension later.
1. Run the app and navigate to http://localhost:3000/search.
2. You should see an unstyled basic search box at the bottom of the page. We can restyle it later.
Type anything in the search box:
- If there's any prefix match on the title, you should see a popup appear (Try "new" and you should see "new one" popup):
- If you are typing stuff that won't have a *prefix match*, you won't see anything pop up
4. Click "new one" in the popup. You should see the exact object returned (we can choose to expand the object later; for now, I'm just outputting basic attributes of it).
6. Don't type anything in the search box, just click it. You should see all results available because this means the user is using the …

Feature/#83: build the basic search feature for search page

---

src/components/search/searchArea.tsx

This PR is for issue #102, intending to perform the same functionality as the "Start Over" function currently available in the GeoBlacklight platform:
I also added the feature that when the user clicks the 'X' on the input button, we should treat it the same as if the user wants to start over (i.e., clear out all filters and reset both results and the input box).
1. Run the app and input "av" in the input box, then click "Search":
2. You should see all results based on the suggestions of "av" returned. Select any filter to apply it.
3. You should see a "Start Over" button appear. Click it.
4. Now all filters and results should be reset to their original status, and the input box should be cleared.
5. Run the app and input "av" in the input box, then click "Search" again. You can perform …

#102: Add a button to start over user search

---

src/components/search/searchArea.tsx

This PR is for #103. The purpose of this PR is to achieve the same function as the filter remembering feature in our GeoBlacklight platform.
1. Run the app and perform filter actions for default results or searched results.
2. You should see that every time you select a filter item, your choice is recorded at the top of the list section as a list of buttons:
3. Click on a button, and you should see that you performed a de-selection action and the result reverse back to your last step:
4. You should also see that if you de-select any filter from the filter list (instead of the button list), the button list automatically updates with your selection.
5. The start-over button will clear out the button list as it does the filter list.

#103: remember filter selection and display on top of the search result

---

src/components/NavBar.tsx
src/components/news/PostList.tsx
src/pages/about.tsx
src/pages/contact.tsx
src/pages/index.tsx

This PR is for #125 , which includes the following items after discussing with the designer:
For CONTACT US page:
- Open social media links in a new tab
- Add these styles to the "Send" button: font-family: 'Nunito'; font-weight: 400;
For MOBILE display (whole site):
-  Change hamburger menu items font size to 1.5rem
-  "Brought to you" on the home page to display vertically aligned icons instead of horizontally displayed icons as we currently have
- Add padding left and right for posts on the News page and "Past Team Members" section on the Above page
1. In the desktop display, go to the "Contact Us" page
2. All social media icons should open the link in the new tab now
3. The 'Send' button should have `font-family: 'Nunito'; font-weight: 400`
4. In the mobile display, open the Hamberger …

#125: Fix style issues on contact us page and mobile display

---

.editorconfig
src/pages/about.tsx
src/pages/advisory.tsx

This PR is for #124 with four checkpoints to improve styles. I added `.editorconfig` which is also included in PR #127 to fix the linting error.
On the Advisory page:
- All 'Read More' buttons in the Core Team section are left-aligned and looks like a text button
- Click the 'Read More' button. In the modal window, the links are Salmon Pink.
On the About page:
- The people on the road illustration image has been removed. The bottom part rose with correct spacing.
- The extra space between the "Past Team Members" title and the body was removed

#124 about and advisory page with lint fix

---

src/components/homepage/buttonwithicon/buttonwithicon.tsx
src/pages/index.tsx

This PR is for #123 except for the last item "Try fixating lines and letting foreground layers overlap (exploration)". The exploration item could involve a longer time thus I'd like to fix existing style issues first.
**Top section**
1. On the home page, the intro text is aligned
2. The 'Learn More' button is clickable and it will make the page scroll to content
3. The 'All news and updates' link now has a font of font-weight: 700 and font size: 1rem
**Access Data & Resources section:**
4. 'Coming soon' in data discovery is not bold anymore
5. The icon opacity is 25% for the data discovery disabled button
6. "Access Data & Resources on SDOH & Place" has been changed to "Access Data & Resources"
7. The border separator's color is #ccc instead of #aaa
8. The margin below the road image has …

#123: Update home page's style based on designer's suggestion

---

.gitignore
src/pages/index.tsx

This PR is for #156. Based on the designer's request, I removed the UChicago logo from the 'brought to you by' section on the homepage. Additionally, I noticed that we don't have .env in .gitignore, so I added it.
Run the app and navigate to the 'brought to you by' section on the homepage. You should see that the UChicago logo has been removed.

#156: Remove UChicago logo from homepage and add .env to .gitignore

---

src/components/map/mapArea.tsx
src/components/search/searchArea.tsx

This PR is for issue #164. Based on the designer's request, temporarily change the points on the discovery map to #7E1CC4. Also, modify the color of the Spatial Resolution Selection to match the Search icon.
I put temporary color codes here. In the future, these will be modified based on the designer's final design
1. Run the app and navigate to the search page.
2. Verify that the map pin color has been changed to purple and the background color of the Spatial Resolution Selection has been changed to MUI blue.

#164 change the point color on map to purple

---

src/components/search/iconText.tsx
src/components/search/resultCard.tsx
src/components/search/searchArea.tsx
tailwind.config.js

This PR is for #172. I created the component to fit the container's size (in the code, I made the example container 499px to simulate the design). We don't have the mobile design, but I aligned the elements vertically for small screens.
Note that we will need new icons. Currently, I just pass an existing icon on the home page to the test component.
-----
- Navigate to the search page; an example result component should be on the top.
- Change to mobile view and check the mobile layout of this component.
-----
During the development, I found that it would be better to define the exact objects under 'meta' field for the SolrObject. 
Originally I have 
``` javascript
export interface SolrObject {
id: string;
title: string;
...
meta: { [key: string]: string | string[] };
...
}
```
but `string …

#172: add result list item component

---

meta/helper/solrObjects.ts
meta/interface/SolrObject.ts

This PR addresses #176. It is a simple update to the Solr object type before moving on to the next stage of UI development. By adding clear types for attributes, we can avoid many "if" loops in the data processing.
I'll continue to update the attributes list while working on #172.

#176: add other meta fields to solrObject type

---

package.json
src/components/search/detailPanel/headerRow/headerRow.tsx
src/components/search/detailPanel/paragraphCard/paragraphCard.tsx
yarn.lock

This PR is for #181. I changed the description, usage tips, and display notes for the HTML rendering style.
Currently, I haven't found any result items to test, but you can modify the code to replace the props value with some HTML code, and the result should be rendered in HTML style.
Please let me know if we want other fields to follow this pattern.

#181: add html parsing to description, usage tips and display_notes

---

src/components/map/mapArea.tsx
src/components/search/detailPanel/headerRow/headerRow.tsx
src/components/search/parentList.tsx
src/components/search/searchArea.tsx
src/components/search/searchArea/searchBox.tsx
src/components/search/searchArea/searchRow.tsx
src/components/search/searchArea/spatialResolutionCheck.tsx
src/pages/search/index.tsx
tailwind.config.js

This PR is for #180. It creates the search panel at the top of the search page based on the new design. This PR still uses the previous methods of handling parameters. After creating the frame page to include all components, the method will be reviewed and updated. Some width ratios in the search area may also be adjusted after including other components on the page.
1. Navigate to the search page. The search area is placed at the top of the screen.
2. For spatial resolution checkboxes, I used the original list of spatial resolutions. Among them, the State and County checkboxes are set to be checked by default and uneditable (we can remove them as well). Other checkboxes can be turned on and off. The map will reflect the changes.
3. The search input field has been modified to reflect the …

#180: create the search component based on the new UI design

---

next.config.js
package.json
yarn.lock

Upgrades to next 13.5.6. This is (was) necessary to support some work on the discovery app, but we need to do it in main as well so that the same build commands are used on all branches (for Netlify).

chore: upgrade next and change export command

---

README.md
public/admin/config.yml
public/styles/posts.module.css
src/components/showcase/ShowcaseItem.tsx
src/components/showcase/ShowcaseLayout.tsx
src/pages/showcase/[showcase].tsx

Adds a bit of help text around the slug field in posts/showcase entries in the CMS. Also a few small style updates, and removing the intro text from the top of showcase pages.

252 better slug handling

---

src/components/search/resultsPanel/resultsPanel.tsx
src/pages/search/index.tsx

This PR addresses the issue of infinite re-rendering in `DiscoverArea` and its subcomponents, which can be observed by adding a console log in the component. The root cause was the `useEffect` in `index.tsx`, which is responsible for providing `solrObjectResults` to all components in `DiscoverArea`. Without dependencies, the `useEffect` was running on every render, causing `setSolrObjectResults` and other state setters to trigger additional renders, leading to the infinite loop.
I've added solrUrl and schema as dependencies, ensuring that `<DiscoverArea>` and its subcomponents only re-render when these two variables change. I also cleaned up some unused code in `index.tsx` after making this change.
Run the app and navigate to the search page. You should observe only two render cycles, as …

Fix the infinitely re-rendering of DiscoverArea and its subcomponents

---

src/components/map/mapArea.tsx
src/components/map/mapButtons.tsx
src/components/search/mapPanel/mapPanel.tsx
src/components/search/searchArea/spatialResolutionCheck.tsx

Some updates to the map component, still more work to do but it's a start.
- Replace layers param handling with `nuqs` per #235
- Add a `bbox` url param to track map panning, and use this param for initial load of map (if present)
- Style zoom to region buttons per mockups
- Add a "Search this area" checkbox and corresponding url param `bboxSearch=true`
@pengyin-shan For future reference, the idea is that if `bboxSearch=true`, then an additional filter will be applied to the search query that casts the value of the `bbox` param (i.e. the current extent of the map view) into a Solr-friendly query and runs against one of the geometry-related fields in the index, like `geometry` or `bounding_box`. In other words, every time the map is moved, the search results will update based on the bbox …

Update map component nuqs

---

meta/glossary.json
src/components/GlossaryPopover.tsx
src/components/search/searchArea/searchRow.tsx

Initial implementation of #257, a "glossary" that can power extra definitions for key terms. It is implemented with a simple MUI popover that has a style matching the buttons within the map interface. The popover appears on click (not on hover) so it should work fine on mobile as well. 
By default, it looks for a predefined entry in the `meta/glossary.json` file, but any content can be passed to it, if there are context-specific definitions we want to display.
To test:
1. go to: https://deploy-preview-270--cheerful-treacle-913a24.netlify.app/search
2. click on the underlined term "health equity" in the text description
We could implement this anywhere within the website, besides news posts and showcase pages (though, it would be possible to set that up). For button labels, we could use …

feat: create popover for glossary items

---

meta/helper/solrObjects.ts
src/components/search/detailPanel/headerRow/headerRow.tsx

Closes #181. The description was being truncated, probably leftover from an earlier implementation where we just wanted to show a snippet of the description. Now fixed.

fix: address bug with HTML display in description field #181

---

src/components/search/searchArea/searchBox.tsx
src/components/search/searchArea/searchRow.tsx

This PR is for #238. It updates the search box to match the new design and adds a "close" button that allows users to reset the search while typing. Note that the auto-complete is not working because `/suggest?` does not return any results at the moment. The Info icon is currently kept as a "/#" link until the corresponding page is designed.
1. Navigate to the search page and type anything in the search box.
2. You should notice an "X" button appears:
3. Click this button, and you should see all search input cleared.
4. Try adding a few spatial resolution filters and then perform a search.
5. Now click the "X" button again. You should see that the filters are maintained, but the result list is refreshed by removing the query.
6. Enter something in the search box, perform the search, and …

#238: Update the search box to match the new design

---

meta/interface/SolrObject.ts
src/components/search/detailPanel/paragraphCard/paragraphCard.tsx

This PR addresses #293. It switches the reference link to display its content.
1. Go to the search page and click one of the result items.
2. The reference link should now display the correct content:

#293: change the reference link content

---

meta/helper/solrObjects.ts
src/components/search/discoveryArea.tsx
src/components/search/filterPanel/filterPanel.tsx
src/components/search/helper/ParameterList.tsx
src/components/search/resultsPanel/resultsPanel.tsx
src/components/search/searchArea/searchBox.tsx
src/components/search/searchArea/searchRow.tsx

This PR is for #265. It enables the auto-suggest feature after the user inputs anything in the search box.
1. Go to the search page and type anything in the search box. You should see the auto-suggestion feature enabled again:
2. Click on one of the results (for example, southwest coastal alaska). You should see the result list appear after the query:
3. Run a sort or filter, and the result list should adjust as expected:
@mradamcox : while fixing the suggestion feature, I noticed an issue that I want to confirm with you. One example is "southeast coastal Alaska," which was suggested by Solr. Our existing rule for generating the parent object from the child object resulted in no results.
When I checked the query (https://solr.sdohplace.org/solr/blacklight-core-dev/select?q=southeast%20coas …

#265: fix the auto suggestor

---

src/components/search/discoveryArea.tsx
src/components/search/filterPanel/filterPanel.tsx
src/components/search/helper/ParameterList.tsx
src/components/search/resultsPanel/resultsPanel.tsx

This PR addresses issue #292. It adds a "Clear All Filters" button to reset all applied filters.
1. Apply any filter. You should see a "Clear All Filters" button appear: <img width="1673" alt="Screenshot 2024-09-19 at 4 38 37 PM" src="https://github.com/user-attachments/assets/157cdb71-34e1-479d-acd8-d3ca952d650d">
2. Click the button, and all filters should be cleared: <img width="1849" alt="Screenshot 2024-09-19 at 4 39 36 PM" src="https://github.com/user-attachments/assets/b3b587f8-41da-4de7-8fea-aa032a3ce3d5">
3. Apply filters until you see a "No results" view. Then, click "Community Health" to navigate to the subject view (Note: no results will be displayed at this time, as I will address the subject icons in a future PR). Afterward, click the "Clear All Filters" button: <img …

#292: Add a reset button to reset filters, including subject

---

meta/helper/solrObjects.ts
src/components/search/discoveryArea.tsx
src/components/search/helper/FilterHelpMethods.tsx
src/components/search/helper/SolrQueryBuilder.tsx
src/pages/search/index.tsx

This PR addresses #306 and #307. It adds pagination (row=1000) to ensure all objects are returned, except those with gbl_suppress_b set to true.
1. Navigate to the search page, where all objects should now be returned, except those excluded (For now you will see the "No result" view, but once the data get updated, you should see the correct output).
2. Test the filters and search functionality to confirm that everything works as expected.

#306, #307: add pagination and remove suppressed objects

---

meta/helper/solrObjects.ts
src/components/search/discoveryArea.tsx
src/components/search/helper/ParameterList.tsx
src/components/search/helper/SolrQueryBuilder.tsx
src/components/search/searchArea/infoPanel.tsx
src/components/search/searchArea/searchBox.tsx
src/components/search/searchArea/searchRow.tsx

This PR addresses #314. It also moves the judgment of unsuppressed documents to the query side.
1. Navigate to the search page and click the info icon in the search box. You should see the information panel appear:
2. Switch tabs, and different content should appear. I have added placeholders for now.
3. Click on the info icon or the close icon. This tab should be replaced by the original search box.

#311: Filter object from the solr side and add info section

---

content/posts/finding-healthy-food-connecticut.mdx
content/posts/introducing-the-sdoh-place-project.mdx
content/posts/mapping-montgomery.mdx
content/posts/place-project-cohort.mdx
content/posts/symposium2024.mdx
content/showcase/sharing-birth-stories-in-the-motherhood-project.mdx
content/showcase/structural-inequality-health-by-gender-sexuality-in-the-u-s.mdx
content/showcase/the-montgomery-alabama-asset-map.mdx
content/showcase/windham-willmantic-conn-food-access-map.mdx
public/styles/posts.module.css
src/styles/globals.css

Headers from the toolkit have Fredoka, so that's what we should use in the MDX content, but that style was being overwritten with Nunito. Fix this, and also slightly increase the size of h3 and h4 so set apart better from standard paragraph text.
Also, with this change, it was apparent that a number of headings in existing MDX content looked like this:
```
```
Which was resulting in extra bold, so I've remove the ** in all these cases as well. There may be more to do on this front in the publish branch, will check that next.

Fix heading style in MDX content

---

content/guides/public-transit-equity.mdx
src/pages/index.tsx

Finalizes the first research guide, with the addition of an "about the author" section. This can serve as a starting point for a later addition to the guide layout template, or perhaps a new custom component we will add to the guides markdown editor.

feat: add one-off author section to transit guide; enable link from homepage

---

public/admin/index.html
src/styles/globals.css

DecapCMS allows us to create custom editor components to render complex Markdown
Fixes #342 
* feat: create a custom editor component that will produce standard `<details>`/`<summary>` toggles as HTML
* Prevent nesting one Toggle Section within another Toggle Section
Example:
Which produces the following HTML:
```html
<details name="example"><summary>1. Access varies depending on where you are (origin)</summary><p>Imagine living in downtown Chicago, where it is easy to catch a bus or hop on the subway to get to work, visit friends, or run errands. If the transit system is well-connected, and stops are just a short walk from your home, this could make it convenient for you to rely on public transportation. Now, if someone lives in a small rural town where public transit might be limited to …
```

feat: register a custom editor component named Toggle Section

---

public/admin/config.yml

There is no easy way for a non-technical user to preview their finalized post before Publishing
Fixes #258 
* feat: use `preview_path` field to point at the location of the unpublished news/showcase/guides piece
1. Navigate to https://deploy-preview-357--cheerful-treacle-913a24.netlify.app/admin/index.html#/collections/guides/entries/example-deleteme?ref=workflow
* You should see an editor/preview for this unpublished draft
* You should see "View Preview" at the top-right
2. Click on the "View Preview" button
* You should see a new tab opens to the Preview from PR #358 
* You should be automatically brought to the path of this guide's preview
* You should see a preview of how the guide will look once it is published

feat: include preview_path for posts/showcases/guides

---

content/showcase/sharing-birth-stories-in-the-motherhood-project.mdx
content/showcase/structural-inequality-health-by-gender-sexuality-in-the-u-s.mdx
content/showcase/the-montgomery-alabama-asset-map.mdx
content/showcase/windham-willmantic-conn-food-access-map.mdx
public/admin/config.yml
src/lib/showcases.ts

Showcase items cannot be easily sorted by date, since we are not tracking the dates they were added
Fixes #303 
* feat: added a new `date` field to Showcase items
* This adds a new `DateTime` widget to the Showcase editor (defaults to the current date, no time)
* This `date` field is not currently displayed on the list of Showcases or when viewing a rendered Showcase :+1:
* Sort ShowcaseList by this new date field (newest to oldest)
* NOTE: This PR does not retroactively add `date` fields to older Showcase items (but I am happy to add these if we know the expected/desired date for each Showcase)
* ~~Old entries without a date are currently tolerated - no extra errors should occur if they are not present~~ date is now required, since we are sorting by it
* To add a `date` to an old entry, …

feat: added "date" field to showcase items

---

src/components/search/detailPanel/detailPanel.tsx
src/components/search/detailPanel/iconTag.tsx
src/components/search/discoveryArea.tsx
src/components/search/filterPanel/filterPanel.tsx
src/components/search/helper/ParameterList.tsx
src/components/search/helper/themeIcons.tsx
src/components/search/resultsPanel/resultsPanel.tsx

This PR addresses #363. It enbles multi-selection for the themes filter.
##How to Test
1. Navigate to the search page and open the filter panel.
2. Select the "Demographic" theme filter, then add the "Employment" filter. You should see the result list length increase due to the additional filter:
3. Open a result detail, and the corresponding theme icon should be highlighted:
4. Experiment with the filters to ensure the list updates as expected.

enable mul-ti selection of the theme filter

---

src/components/search/discoveryArea.tsx
src/components/search/searchArea/searchBox.tsx

This PR addresses issue #381. It forces the search text box to refocus after the user removes all their input. I also removed some unused legacy code from discoveryApp.tsx.
##How to Test
1. Navigate to the search page and start typing in the search box.
2. Delete all input using the keyboard, and you should see that the search box remains focused after everything is cleared.

#381: Force the search box to refocus after the input got cleared out

---

meta/helper/solrObjects.ts
meta/interface/SolrObject.ts
src/components/search/helper/CleanHtml.tsx
src/components/search/helper/FilterByScore.tsx
src/components/search/helper/SolrQueryBuilder.tsx
src/components/search/resultsPanel/index.tsx
src/components/search/resultsPanel/resultCard.tsx
src/components/search/searchArea/searchBox.tsx
src/components/search/searchArea/spellCheckMessage.tsx
src/middleware/createMiddleware.ts
src/store/selectors/SearchSelector.ts
src/store/slices/searchSlice.ts
src/store/types/search.ts

This PR addresses #405, #409, and #412, reflecting front-end updates that align with changes made in https://github.com/healthyregions/SDOHPlace-MetadataManager/pull/37. Its main features include:
1. Enhanced Scoring Mechanism
A more scientific approach has been implemented to select items for the result list. Instead of relying on a fixed score threshold, a method was added to dynamically detect sharp score drops among results. Only items with acceptable score drops are included, while the rest are filtered out.
2. Tooltips for Transparency
Tooltips now display highlights from key fields, along with the score and a brief description of relevance. For related results, tooltips also indicate the targeted term for the result, helping users understand when a different but relevant term is …

#405, #409, #412: add support for highlight, spellcheck and better score mechanism

---

src/components/search/helper/CleanHtml.tsx
src/store/slices/searchSlice.ts
src/store/types/search.ts

This PR addresses issue #416 and removes the default sorting configuration from the front-end. The corresponding Solr configuration is available in [SDOHPlace-MetadataManager PR #39](https://github.com/healthyregions/SDOHPlace-MetadataManager/pull/39).
1. Navigate to search page. You should see that results are sorted by title by default.
2. Perform any search. Results should now be sorted by score.
3. Clear the search term in the Search Box. A re-fetch action should be triggered, and the results should once again be sorted by title.

#416: remove the initial state on sort

---

src/components/NavBar.tsx

fix a small issue with the logo link, related to #426

fix: set non-relative path for logo image asset #426

---

meta/interface/SolrObject.ts
src/components/map/dynamicMap.tsx
src/components/map/geoSearchControl.tsx
src/components/map/helper/layers.tsx
src/components/map/helper/sources.tsx
src/components/map/mapArea.tsx
src/components/search/detailPanel/iconTag.tsx
src/components/search/discoveryArea.tsx
src/components/search/mapPanel/index.tsx
src/components/search/mapPanel/mapPanelContent.tsx
src/components/search/resultsPanel/index.tsx
src/components/search/resultsPanel/resultCard.tsx
src/components/search/searchArea/searchBox.tsx
src/components/search/searchArea/spatialResolutionCheck.tsx
src/middleware/actionConfig.ts
src/middleware/filterHelper.ts
src/store/slices/searchSlice.ts
src/store/slices/uiSlice.ts
src/store/types/search.ts
tsconfig.json

This PR adds a new feature that allows users to check a box on each result item to add a preview layer to the map that shows the spatial coverage for a given dataset.
Closes #408 
We had something like this before on hover of the result item, but this is more explicit, and the implementation also offers a lot more flexibility in how the preview layer is constructed.
In the metadata schema we have a field "Highlight IDs" that must be filled out with one or more "HEROP_IDs", and that field powers this preview. The first three characters of a HEROP_ID denote what geography level the rest of the ID pertains to, and this is used to denote what geography layer is used for the preview layer. For a full explanation of HEROP_IDs, see: https://github.com/healthyregions. There are two ways to fill …

408 display spatial coverage

---

src/components/search/mapPanel/mapPanelContent.tsx
src/components/search/searchArea/index.tsx
src/components/search/searchArea/infoPanel.tsx
src/components/search/searchArea/spatialResolutionCheck.tsx
src/store/slices/uiSlice.ts

We have been in need of more help text since it was identified as a shortcoming in the superuser meeting. Additionally, we had determined that the info box could be used thoroughly within the app, and it could be activated by click events outside of the single "i" icon in the search box.
I'm starting this PR as a work in progress so we can get a preview deploy going. Initially, I have focused on the box itself rather than the content.
- move the active tab id to a global store so it can be set from anywhere within the app
- added a "get started" link in the left-hand text, to directly open the box
- added "next/previous" links at the bottom of each tab to create a better "on-boarding"-style flow.
- changed the overlays info icon to now open a new overlays tab in the info box (content …

Improved help text

---

src/components/search/discoveryArea.tsx
src/components/search/resultsPanel/resultCard.tsx
src/components/search/searchArea/index.tsx
src/styles/globals.css

Our designs for Result Cards within the Discovery App have changed
* style: adjust styling / layout to match new designs
Before:
After:
1. Navigate to https://deploy-preview-437--cheerful-treacle-913a24.netlify.app/search
* You should see result cards listed on the left side
* You should see that the layout / styling has been adjusted to match [the latest designs](https://www.figma.com/design/vD6pC3DsFtGG2aCv4vWXtV/HEROP?node-id=3099-1201&t=Pf64kLoNiSa6xio2-0)

style: adjust styling for result cards within the Discovery App

---

src/components/search/resultsPanel/resultCard.tsx

We would like to disable/clear existing map preview when the user clicks "Show on map"
Fixes #440
* feat: remove spread operator to implement "radio" behavior for map coverage/preview
1. Navigate to https://deploy-preview-442--cheerful-treacle-913a24.netlify.app/search
* You should see results listed on the left side
* You should see "Show on map" listed on the top-right of each result card
* NOTE: some buttons may be disabled here if there are no Highlight IDs set up in the Metadata Manager
2. Click the "Show on map" button beside one result
* You should see that the button text changes to "Remove preview" - this signifies that the result is now being shown on the map
* After a few seconds, you should see the preview layer appear on the map
3. Choose a different result card and click …

feat: remove existing map previews/coverage when new result is clicked

---

src/pages/news/[post].tsx

This problem was located in #461 
When creating a new post, if `tags` are not defined in the frontmatter then the build/publish step can fail
For example:
https://github.com/healthyregions/SDOHPlace/pull/461/files#diff-0a533058926c6579ba4e5f979149f98902edf0d0aab98da670a6d891c2b96256R1-R10
* fix: fallback to empty array if undefined/null tags are encountered
1. Create a post without specifying any `tags`
2. Click Publish and verify that the build completes successfully

fix: null object pattern - use empty array if tags are undefined/null

---

src/components/search/mapPanel/mapPanelContent.tsx

On the Discovery App (Search view), when the Overlays dropdown is open we see a mysterious shadow element appear all the way down the right side of the app
We want to hide/remove this element when the dropdown is open
Fixes #462 
* fix: remove the shadow element that appears when the Overlays dropdown is open
1. Navigate to https://deploy-preview-465--cheerful-treacle-913a24.netlify.app/search
2. Click the Overlays dropdown on the top-right
* You should see that the dropdown opens to show the Overlays that we offer
* You should not see a shadow / extra box appear over the scroll bar on the right
* Compare with https://discovery_app.dev.sdohplace.org/search?query=*

fix: remove "shadow element" that appears when Overlays dropdown is open

---

src/components/search/resultsPanel/index.tsx

This PR introduces a bottom margin between the expandable filter panel and the first result item, improving visual separation. Previously, the panel and the first result appeared too close together:
1. Navigate to the search page and expand the filter panel.
2. You should now see a visible gap between the bottom of the panel and the first result item:

#471: Add more bottom margin to the filter panel when it is on

---

src/components/map/dynamicMap.tsx
src/components/search/searchArea/enhancedSearch.tsx

On the Search view, GeoSearchControl fails to clear when user clicks the X button
An error appears in the console:
```
740.51aeb2356eba5b27.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'properties')
at ns.<anonymous> (740.51aeb2356eba5b27.js:1:3999)
at ns.fire (d94c0b71.5ec4673aaae53c8c.js:4:9879)
at ea.<anonymous> (193.5f094c41bb516592.js:42:30141)
at 193.5f094c41bb516592.js:21:81687
at Array.forEach (<anonymous>)
at 193.5f094c41bb516592.js:21:81673
at e.$$.update (193.5f094c41bb516592.js:21:88453)
at 193.5f094c41bb516592.js:21:44380
at Ti (193.5f094c41bb516592.js:21:44498)
```
Fixes #464 
* fix: only send Plausible event with extra data if there is extra data to send - otherwise, no-op and do not send the event 
1. Navigate to …

fix: added null checks for Plausible events related to Search

---

src/components/search/discoveryArea.tsx
src/middleware/createMiddleware.ts

This PR fixes issue #470, resolving a bug that prevented the detail view from appearing when users copied and pasted a URL containing the `show=` parameter.
1. Navigate to the search page and click "Details" on any result item to open the detail view.
2. Click "Share" to generate a shared link, then copy and paste the URL into a new tab or window.
3. The detail view should be displayed by default on the newly opened page.

#470: Fix show detail

---

src/components/map/dynamicMap.tsx
src/components/map/helper/layers.tsx
src/components/map/helper/sources.tsx
src/components/search/searchArea/infoPanel.tsx

To address #459 I've changes the way overlays are defined and added a "cluster" strategy to the layer creation.
Importantly, this _also_ relies on having a pmtiles file source that has been created with some level of clustering. Currently, I'm using these arguments with tippecanoe to make the file:
```
tippecanoe nei-facilities.geojson -z10 --cluster-distance 10 --cluster-maxzoom g -r1 -d 20 --projection=EPSG:4326 -l resources --force -o nei-facilities.pmtiles
```
In the future we made need to tweak these settings, like the cluster distance and maxzoom, but the result is workable for now.
There is a click interaction that will zoom you in one level if you click on a clustered point, and there is a popup that will show if you click on a non-clustered point, and this now shows all …

Overlay clusters

---

src/components/search/discoveryArea.tsx

We would like to add a banner letting people know that this is a new platform and we are open to feedback and potential future directions
Fixes #478 
* feat: added the banner as it appears in the [Figma designs](https://www.figma.com/design/vD6pC3DsFtGG2aCv4vWXtV/HEROP?node-id=3209-609&t=uwESnBJNhgvo3Afk-0)
TODO: banner URL does not currently work, but once form is live this link should work correctly
TODO: should banner URL be parameterized? not clear how often or if ever it would change in the future 🤔 
1. Navigate to https://deploy-preview-483--cheerful-treacle-913a24.netlify.app/search
* You should see the banner now appears below the page header / search area
* You should see a link is offered in the banner
2. Click the link in the banner
* You should see that the [Feedback …

feat: add banner for soft launch

---

src/components/search/helper/FilterByScore.tsx
src/components/search/resultsPanel/index.tsx
src/store/slices/searchSlice.ts

This PR integrates the "You may be interested in..." related results section that we currently have in prod into the main search results section, reducing unnecessary scrolling for users.
1. Navigate to https://deploy-preview-467--cheerful-treacle-913a24.netlify.app/search and search for "mean".
- You should see 17 (5+12) results in total, which matches the combined number of search results and related suggestions in the production environment (https://discovery_app.dev.sdohplace.org/search?query=mean).
- Screenshot:
2. Review the Results
- Skim through the list to verify that the related results are now seamlessly integrated.
- The tooltip text for "You may be interested in..." suggestions has been updated to:`You may find <b>${q}</b> in this result relevant for <i>${currentQuery}</i>.`: …

#460: Append the suggested result to the end of the search result

---

src/components/search/detailPanel/introCard.tsx
src/components/search/resultsPanel/resultCard.tsx

We would like to add some spacing on the Result Card and remove padding from the Item Details Intro Card
Closes #480 
* style: added spacing on result card and removed padding from item details
1. Navigate to https://deploy-preview-484--cheerful-treacle-913a24.netlify.app/search
* You should see results are listed on the left side
* You should see that the space between the 2 columns at the bottom of each Result Card has been increased
2. Choose a result and click "Details"
* You should see the Details View appear
* You should see that the Intro Card section (just below the first orange horizontal line) is now aligned with the orange line

style: added spacing on result card and removed padding from item details

---

src/components/map/dynamicMap.tsx
src/components/search/discoveryArea.tsx
src/components/search/filterPanel/sortOptions.tsx
src/components/search/filterPanel/yearRangeSlider.tsx
src/components/search/searchArea/enhancedSearch.tsx
src/components/search/searchArea/spellCheckMessage.tsx
src/middleware/actionConfig.ts
src/middleware/createMiddleware.ts
src/middleware/filterHelper.ts
src/store/slices/searchSlice.ts
src/store/types/search.ts

This PR fixes #472, #481, #482 and #488. It addresses occasional race conditions that occur when triggering filters, as well as an occasional double-trigger of data fetching during initialization. To resolve these issues, I have implemented a request ID mechanism and adjusted the trigger points for fetch activities, as well as re-organized reset filter methods. These changes should help prevent unintended behavior.
1. Navigate to the search page and test the three sort options. They should function correctly, with the appropriate underline highlighting the current sorting option for #482:
*(Compare this to the current behavior at https://discovery_app.dev.sdohplace.org/search)
2. Perform various filtering actions to verify they work as expected. Then, copy the URL (or use the 'Share' …

#472,#481,#482, #488: adjust filter mechanism to avoid possible racing condition and minor bug fixes

---

src/components/search/searchArea/enhancedSearch.tsx
src/components/search/searchArea/helpText/aiSearchText.tsx
src/components/search/searchArea/helpText/communityAssetsText.tsx
src/components/search/searchArea/helpText/geographyFilterText.tsx
src/components/search/searchArea/helpText/infoHelpText.tsx
src/components/search/searchArea/helpText/keywordSearchText.tsx
src/components/search/searchArea/helpText/searchResultsText.tsx
src/components/search/searchArea/infoPanel.tsx

This PR addresses #490, refining the AI search help text for improved user-friendliness. During the revision, I also separated each help text component from the infoPanel for easier management and increased the character limit for AI-based questions to accommodate more complex queries.
1. Navigate to https://deploy-preview-505--cheerful-treacle-913a24.netlify.app/search and open the AI search (experimental) section.
2. Review the updated help text.

#490: Update AI-search help text

---

src/components/homepage/buttonwithicon/buttonwithicon.tsx
src/components/search/detailPanel/headerRow.tsx
src/components/search/detailPanel/introCard.tsx
src/components/search/detailPanel/paragraphCard/paragraphCard.tsx

We have another set of small styling changes that we would like to apply to the Discovery App search page
Fixes #480 
Fixes #498 
* style: search/headerRow align icon/buttons with start of div
* style: search/introCard add bottom padding on right side to match the top
* style: search/paragraphCard remove left padding on More links section
* style: search/headerRow added External Link (aka Launch) icon to "Go to Resources" button
1. Navigate to https://deploy-preview-504--cheerful-treacle-913a24.netlify.app/search
* You should see the Discovery App search page is loaded
* You should see search results listed on the left side
2. Choose a search result and click the "Details ->" button
* You should see the right panel change to the Item Details view for the selected search result
* You …

style: minor adjustments to Item Details

---

public/admin/config.yml
src/pages/advisory.tsx
src/pages/fellows.tsx

Our current Fellows page only displays the Spring 2024 cohorts
We would like to update this view to display and organize fellows from multiple different cohorts
Fixes #364 
* fix: reword the Advisory page - Past Advisory Board Members -> Project Launch Advisory
* feat: rework the Fellows page to support multiple cohorts
1. Navigate to https://deploy-preview-512--cheerful-treacle-913a24.netlify.app/fellows
* You should see the view now displays Spring 2024 Fellows
* Once we add Fall 2024, you should see them displayed above Spring 2024 (since they are more recent)
* Similarly, once we add the Spring 2025 Cohorts, they will appear above the 2024 ones

feat: rework the fellows page to support multiple cohorts

---

src/components/search/resultsPanel/index.tsx
src/components/search/searchArea/infoPanel.tsx
src/styles/globals.css

This PR addresses issue #496. It applies the styling approach introduced by @shubhamk008 to add a permanent scrollbar to the result list and the help-information section. I have tested it on Chrome, Edge, and Safari on my MacBook.
Note that the WebKit-based solution does not work for Firefox (https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar). While a non-WebKit method can alter the scrollbar’s appearance (like https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling), it does not ensure a permanently visible scrollbar. Instead, users can enable this feature manually in Firefox settings (https://connect.mozilla.org/t5/discussions/scrollbars-disappear-in-firefox-100/m-p/6358). If I missed any relevant resources, please let me know—I did some searches but …

#496 agnostic scrollbar

---

src/components/search/searchArea/helpText/aiSearchText.tsx

This PR addresses issue #517. It clarifies that AI-Search results are filtered by location when specified in the user's query. However, this filtering is not yet visually reflected on the map or filter panel, which may confuse some users when they see filtered results without corresponding map updates.
1. Navigate to the search page and open the help panel for AI-Search.
2. An additional explanation should now appear at the end of the help text:

#517: Update ai-search help text to explain current limitation

---

src/components/search/resultsPanel/index.tsx

This PR addresses issue #525 by adding filterStatus props to the payload passed to Pausible in the 'No Result' view.
As discussed in the ticket, most occurrences of "No Search Results" happen when multiple filters are applied, since the recommendation mechanism attempts to prevent 'No Result' views for single searches.
To enhance visibility into filter usage, this PR introduces two new props:
1. One represents filters as an array.
2. The other provides a more comprehensive string format.
Since it's unclear which format will perform better, both can be included initially. Once Pausible starts receiving results, we can remove any unnecessary props. With this change, we will be able to see the applied filters and their values when a user encounters a 'No Result' view.

#525: Add filter status to Pausible payload to check for no result search

---

content/guides/public-transit-equity.mdx
src/styles/globals.css

Currently, images use 100% of the page width
But some of these images are purely decorative and don't need to draw that much of the user's focus
Fixes #540 
* feat: allow users to specify which images are decorative - these will be given 50% width (on large screens only)
* smaller screens should still use 100% width
* we could also add a "Decorative Image" widget that would add this div/class around the given image, which might ease user experience a bit if folks aren't as familiar with HTML
For example:
```
<div className="decorative-image">
</div>
```
On larger screens, this will render as:
On smaller screens, this will render as:
~~I'm not sure how to offer a test case via Netlify, as I believe DecapCMS will create a new branch/PR for each change
But to use the new class, it would need …

#540 feat: decorative images in markdown

---

content/guides/public-transit-equity.mdx
public/admin/config.yml
public/admin/index.html
public/styles/posts.module.css
src/components/Layout.tsx
src/components/NavBar.tsx
src/components/guides/GuidesItem.tsx
src/components/guides/GuidesLayout.tsx
src/components/guides/GuidesList.tsx
src/lib/guides.ts
src/pages/guides/[guide].tsx
src/pages/guides/index.tsx
src/styles/globals.css

We need a generic way to link from SDOH guides to the Discovery App
It would be nice if this solution was generic enough to be reused for other things as well
Fixes #541 
* feat: added a custom Panel component to the Markdown editor with the following properties:
* `title`: Header to display at the top of the panel
* `content`: Markdown body to display on the right side of the panel
* `link`: URL for the link at the bottom of the panel
* `linkText`: Text to display for the link at the bottom of the panel
* `image`: Image to display on the left side of the panel
* `backgroundColor`: Background color to use for this panel
TBD

#541 feat: add generic Panel component for markdown editor

---

src/components/search/detailPanel/iconTag.tsx
src/components/search/discoveryArea.tsx
src/components/search/helper/SolrQueryBuilder.tsx
src/components/search/helper/themeIcons.tsx
src/components/search/resultsPanel/index.tsx
src/components/search/resultsPanel/resultCard.tsx
src/components/search/searchArea/enhancedSearch.tsx
src/middleware/createMiddleware.ts
src/store/slices/searchSlice.ts
src/store/types/search.ts

This PR addresses issues #549, #542, and #546. It updates the default behavior of the autocomplete dropdown in the search box to prevent pre-selection when the user's mouse moves out of the dropdown area. It also fixes some bugs related to the "No Results" scenarios and includes general code optimizations.
1. #542: Go to the search page and type a keyword longer than two characters to trigger the autocomplete dropdown (e.g., "scocial").
2. Hover over a suggestion, then move your mouse out of the dropdown.
3. Previously, the first item would be automatically highlighted (shado
wed), but now this is no longer the case.
4. Press Enter after moving your mouse out — the search should be performed using your typed input (e.g. "social"), not the first suggestion.
5. #546: Type a short term that …

#549, #542, #546: Fix the related term bug and update search box autocomplete behavior

---

src/components/Layout.tsx
src/components/NavBar.tsx
src/components/guides/GuidesItem.tsx
src/components/guides/GuidesLayout.tsx
src/components/guides/GuidesList.tsx
src/components/showcase/ShowcaseItem.tsx
src/lib/guides.ts
src/pages/guides/[guide].tsx
src/pages/guides/index.tsx
src/pages/showcase/index.tsx

While they are listed on the homepage, we don't currently offer a page where we list our SDOH Guides (similar to the News and Showcase sections)
Fixes #479 
* feat: added the `/guides` page that lists all SDOH Guides within DecapCMS
* fix: uncommented Resources > SDOH Guides in the NavBar
* TODO: need to determine what text to use for intro paragraph
1. Navigate to https://deploy-preview-539--cheerful-treacle-913a24.netlify.app/guides
* You should see a page here that lists all existing Guides in the system
2. Click on a Guide (e.g. Public Transit Equity)
* You should be brought to the Guide that you clicked
* You should see the Guide contents rendered from markdown

#479 feat: added a dedicated page to list SDOH Guides

---

src/pages/advisory.tsx

There was an expectation on the frontend that advisory board member profiles would always have one or more links attached. This caused the error in #588 because some new entries don't have a link.
Edit: That's not quite correct, the assumption was actually that `links` would always be an array (no problem if it was empty) but on these new entries `links` was just not present as an attribute at all, thus the error with `map` and `undefined`.
closes #588

fix: don't error if there aren't links #588

---

src/components/search/mapPanel/mapPanelContent.tsx

close #633. Fixed link to guide suggestion/application form from discovery application front page.
(note: It had already been changed in the `develop` branch, but it had been changed to `/contact` where it should have been changed to the external form link. All set now.)

fix: fix problem with guide application link, #633

---

src/components/search/searchArea/helpText/communityAssetsText.tsx

Added a note to address one part of #626:
@shubhamk008 Let me know how this should be changed to make it ready to go.

docs: add note about community asset layer accuracy

---

meta/interface/SolrObject.ts
src/components/search/detailPanel/headerRow.tsx

This PR makes a small modification to the data discovery app, specifically the description part of the details page for a result item. Before, the description was pushed into a single div. Now, the description array is iterated, each one sanitized (as before) and then each pushed into its own div.
To test:
- Compare existing rendering:
- https://sdohplace.org/search?query=Environmental+Justice+Index&show=herop-oqxqog
- with updated rendering:
- https://deploy-preview-677--cheerful-treacle-913a24.netlify.app/search?query=Environmental+Justice+Index&show=herop-oqxqog

676 display multiple descriptions
